### ISSUE TITLE
Multiple questions about the use of ILL.ILL.Ass

### ISSUE THREAD

**Issue by Akatmks** [klsruan/ILL-Aegisub-Scripts#4]
I'm still trying to figure out how to use ILL. Forgive me if I made any mistakes :)

I wonder if I may ask what's the purpose of copying the line in `Ass.iterSel` and `Ass.iterSub`?  
Because of the nature of `@i` in `Ass.iterSel` and `Ass.iterSub`, I assume the user should only modify the subtitle object using `Ass.setLine`, `Ass.insertLine` and `Ass.removeLine`. However, `l` can not be used on these functions:  
```lua
main = function(sub, sel, act)
    local ass
    
    ass = Ass(sub, sel, act)
    for l, line, s, i, n in ass:iterSel() do
        ass:progressLine(s, i, n)
        ass:insertLine(l, s)
    end

    return ass:getNewSelection()
end
```
```
Lua reported a runtime error:
    File "?data\automation\autoload\aka.Testing.lua", line 72
<anonymous function at lines 65-84>
    File "?data\automation\include\ILL\ILL\Ass\Ass.moon", line 135
insertLine
    File "?data\automation\include\ILL\ILL\Ass\Ass.moon", line 191
setText
attempt to concatenate field 'text_stripped' (a nil value)
```

`l` is also not able to be processed by `Line.process` and `Line.extend`, both of which will give it the `text_stripped` field, which will then enable them to be `Ass.setLine` or `Ass.insertLine`.  
```lua
main = function(sub, sel, act)
    local ass
    
    ass = Ass(sub, sel, act)
    for l, line, s, i, n in ass:iterSel() do
        ass:progressLine(s, i, n)
        Line.process(ass, l, i)
        ass:insertLine(l, s)
    end

    return ass:getNewSelection()
end
```
```log
Lua reported a runtime error:
    File "?data\automation\autoload\aka.Testing.lua", line 71
<anonymous function at lines 65-84>
    File "?data\automation\include\ILL\ILL\Ass\Line.moon", line 25
process
attempt to call method 'moveToFirstLayer' (a nil value)
```

**Comment by Akatmks** [comment]
I just realised that `Ass.removeLine` can only be called with `l` but not `line` because `Ass.setText` is not used here.  
```lua
	-- removes a line in dialogs
	removeLine: (l, s) =>
		i = s + @i
		l.comment = true
		@sub[i] = l -- ← Here
		l.comment = false
		if @remLine
			@sub.delete i
			@i -= 1
			@activeLine -= 1
```

**Comment by Akatmks** [comment]
Another thing I'm not sure if it is intentional is that `Ass.setText` is directly applied onto the line passed into the `Ass.setLine` or `Ass.insertLine`. That will revert the `text` field of the line back to `string` instead of `ILL.ILL.Text`, which means I can't use the line after one `Ass.setLine` or `Ass.insertLine`.

**Comment by klsruan** [comment]
> I'm still trying to figure out how to use ILL. Forgive me if I made any mistakes :)
> 
> I wonder if I may ask what's the purpose of copying the line in `Ass.iterSel` and `Ass.iterSub`? Because of the nature of `@i` in `Ass.iterSel` and `Ass.iterSub`, I assume the user should only modify the subtitle object using `Ass.setLine`, `Ass.insertLine` and `Ass.removeLine`. However, `l` can not be used on these functions:
> 
> ```lua
> main = function(sub, sel, act)
>     local ass
>     
>     ass = Ass(sub, sel, act)
>     for l, line, s, i, n in ass:iterSel() do
>         ass:progressLine(s, i, n)
>         ass:insertLine(l, s)
>     end
> 
>     return ass:getNewSelection()
> end
> ```
> 
> ```
> Lua reported a runtime error:
>     File "?data\automation\autoload\aka.Testing.lua", line 72
> <anonymous function at lines 65-84>
>     File "?data\automation\include\ILL\ILL\Ass\Ass.moon", line 135
> insertLine
>     File "?data\automation\include\ILL\ILL\Ass\Ass.moon", line 191
> setText
> attempt to concatenate field 'text_stripped' (a nil value)
> ```
> 
> `l` is also not able to be processed by `Line.process` and `Line.extend`, both of which will give it the `text_stripped` field, which will then enable them to be `Ass.setLine` or `Ass.insertLine`.
> 
> ```lua
> main = function(sub, sel, act)
>     local ass
>     
>     ass = Ass(sub, sel, act)
>     for l, line, s, i, n in ass:iterSel() do
>         ass:progressLine(s, i, n)
>         Line.process(ass, l, i)
>         ass:insertLine(l, s)
>     end
> 
>     return ass:getNewSelection()
> end
> ```
> 
> ```
> Lua reported a runtime error:
>     File "?data\automation\autoload\aka.Testing.lua", line 71
> <anonymous function at lines 65-84>
>     File "?data\automation\include\ILL\ILL\Ass\Line.moon", line 25
> process
> attempt to call method 'moveToFirstLayer' (a nil value)
> ```

In fact, it is remarkable that the first `l` value found in the `iterSub` and `iterSel` metamethods is almost useless, I had already discussed this with Alen, and I decided to leave it like this so that whoever eventually uses our lib would also have access to the raw `line` provided by Aegisub. So to have access to the other functionalities of `class Line` it is necessary to use the `line` object. Anyway part of this problem will be fixed in the next update, because I changed the function `Ass.setText` that will now set the text in a much simpler and functional way

**Comment by klsruan** [comment]
> I just realised that `Ass.removeLine` can only be called with `l` but not `line` because `Ass.setText` is not used here.
> 
> ```lua
> 	-- removes a line in dialogs
> 	removeLine: (l, s) =>
> 		i = s + @i
> 		l.comment = true
> 		@sub[i] = l -- ← Here
> 		l.comment = false
> 		if @remLine
> 			@sub.delete i
> 			@i -= 1
> 			@activeLine -= 1
> ```

Idk if it makes much sense to remove a line that has already been added, in this case the original line would be the line of object `l`, so I didn't worry about that, but that will be solved

**Comment by klsruan** [comment]
> Another thing I'm not sure if it is intentional is that `Ass.setText` is directly applied onto the line passed into the `Ass.setLine` or `Ass.insertLine`. That will revert the `text` field of the line back to `string` instead of `ILL.ILL.Text`, which means I can't use the line after one `Ass.setLine` or `Ass.insertLine`.

You are right, this was also solved by the modification I made to the `Ass.setText` function

**Comment by Akatmks** [comment]
Thank you! I think I can finish my current script without any further issues. Btw is it more convenient to ping you on Discord or send GitHub Issues like this?
