### ISSUE TITLE
[Table.view] The key for Lua table could be table, userdata and more

### ISSUE THREAD

**Issue by Akatmks** [klsruan/ILL-Aegisub-Scripts#5]
<img align="right" width="400" src="https://user-images.githubusercontent.com/112813970/230573129-82ddcee5-1b65-49c6-b27f-310d97848433.png" />  

Table.view [treats](https://github.com/klsruan/ILL-Aegisub-Scripts/blob/main/modules/ILL/ILL/Table.moon#L90-L98) all the table keys that are not function, number or boolean something that needs a quotation mark. In my opinion, maybe only string needs the quotation mark?  

Thank you!

**Comment by klsruan** [comment]
The purpose of this function is entirely for debugging

**Comment by Akatmks** [comment]
Yeah, I used it for debugging as well. That's why I was a little bit puzzled and unsure if the table's key in the screenshot is actually string or userdata. I believe removing the quotation mark will be able to clear this confusion.

**Comment by Akatmks** [comment]
Or to say it in another way:
Changing from 
```moon
			elseif (type(o) == "number") or (type(o) == "boolean")
				return so
			string.format "%q", so
```
to
```moon
			elseif type(o) == "string"
				return string.format "%q", so
			so
```
